# Generated by Django 3.1.4 on 2020-12-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0002_auto_20201214_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=5000)),
            ],
        ),
    ]
