# Generated by Django 3.1.4 on 2020-12-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0003_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='disease',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='description',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
