# Generated by Django 3.1.4 on 2020-12-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0004_auto_20201218_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='show_symptoms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('disease', models.CharField(max_length=250)),
                ('symptom', models.TextField(max_length=5000)),
            ],
        ),
    ]
