# Generated by Django 3.1.4 on 2020-12-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0005_show_symptoms'),
    ]

    operations = [
        migrations.CreateModel(
            name='database',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('disease', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=5000)),
                ('precaution', models.TextField(max_length=5000)),
                ('symptom', models.TextField(max_length=5000)),
            ],
        ),
        migrations.DeleteModel(
            name='description',
        ),
        migrations.DeleteModel(
            name='show_symptoms',
        ),
    ]
