# Generated by Django 3.1.4 on 2020-12-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0006_auto_20201219_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='diseaseDB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('disease', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=5000)),
                ('precaution', models.TextField(max_length=5000)),
                ('symptom', models.TextField(max_length=5000)),
                ('cause', models.TextField(max_length=5000)),
            ],
        ),
    ]
