# Generated by Django 3.1.4 on 2020-12-19 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0007_diseasedb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='diseaseDB',
        ),
    ]
