# Generated by Django 3.1.4 on 2020-12-19 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0008_delete_diseasedb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
