# Generated by Django 3.1.4 on 2020-12-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0009_delete_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='doc_DB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Doctor', models.CharField(max_length=250)),
                ('Type', models.CharField(max_length=250)),
                ('Pincode', models.CharField(max_length=250)),
            ],
        ),
    ]
